### PR TITLE
Add "Approve Permissions" button for iOS for Camera

### PR DESCRIPTION
**Pull request by tinaroh**
The library is because the app settings path constant is only exposed from the iOS native code

### CODE REVIEW

**Comment by tinaroh** [comment]
dang uh.. will look into test failures after figuring out config

**Comment by tinaroh** [comment]
```
 /home/circleci/raha-mobile-app/node_modules/react-native-app-settings/index.js:2
    import { NativeModules } from 'react-native';
    ^^^^^^

    SyntaxError: Unexpected token import
```

@osdiab do you know how I can get jest to recognize "import" lol

**Comment by osdiab** [comment]
Oh Probably need to add react-native-app-settings to the ignore paths in
jest.config.js - Check the comment there

**Comment by tinaroh** [comment]
Updated, please take a look!

**Pull request merged**
