### PR TITLE
Bump RN Firebase version to v5.1.1.

### PR DESCRIPTION
**Pull request by rahulgi**
This results in major dependency jumps for associated firebase
libraries (notably google-play-services base which goes from 15 to 16 
on Android and iOS Firebase Pods which go from 5.3 to 5.11).

This commit also adds the Firestore dependency.

I successfully built and tested the app on Android. Successfully built
for iOS but would appreciate if either of you, @tinaroh and @osdiab,
could try installing it on your iOS device and playing around with it
to make sure everything still looks good.

### CODE REVIEW

**Comment by tinaroh** [comment]
I won't have my iPad for the next two days, sorry. @osdiab can you test for him?

**Comment by osdiab** [comment]
Sure will do later today

**Comment by osdiab** [comment]
Checked, it seems to work for logging in via text, uploading verification videos.

**Comment by osdiab** [comment]
man, committing all these dependencies is so big lol

**Comment by rahulgi** [comment]
excellent. yeah it's pretty crazy lol

**Pull request merged**
