### PR TITLE
Add unverified label to MemberName component.

### PR DESCRIPTION
**Pull request by rahulgi**
screenshot_20180927-175042

### CODE REVIEW

**Comment by rahulgi** [comment]
Not totally sure about the smaller font size.. what do you guys think?

**Comment by rahulgi** [comment]
Also.. open to suggestions other than directly modifying the `MemberName` component.. though it seemed like the simplest way to make sure there aren't places where we forget to label a member.

**Comment by tinaroh** [comment]
Hm I think it would be fine as the same font size actually since it looks kinda funky inline in the feed. I'm okay with sticking it in MemberName component

**Comment by osdiab** [comment]
I also think that putting it next to the name is likely to run into issues with wrapping/running off the side, for people with really long names like you.

**Comment by osdiab** [comment]
On further thought it doesn't seem scalable in general, so i added more ideas to that whimsical.

**Comment by osdiab** [comment]
Talked offline, looks like Profile can use a rework altogether so for now this is a stopgap to change later.

**Pull request merged**
