### PR TITLE
Fix app name for Android

### PR DESCRIPTION
**Pull request by tinaroh**

### CODE REVIEW

**Comment by rahulgi** [comment]
@tina this is changing the published bundle ID? Will the app store transparently handle this change for people who already have the app installed?

**Comment by tinaroh** [comment]
We were already publishing with `assembleProdRelease`. We're not changing anything. But for some reason the productFlavor settings were not getting applied when I built without this change so when you open activity manager the name of the app was the default `app.raha.mobile.MainActivity` or whatever. 

I can try to dig more into why it's not getting applied though.

**Comment by tinaroh** [comment]
BTW, bundle ID is an iOS concept. Product flavor is not something shown to the end user, it's a way to tell the build system what configurations to use.

**Comment by rahulgi** [comment]
ah okay, gotcha. LGTM, thanks!

**Comment by tinaroh** [comment]
I'm actually going to close this. Just built again and wasn't able to reproduce my issue from yesterday... Maybe something up with my phone...

**Pull request closed without merging**
